"""make users company_id nullable

Revision ID: 163afc80d70d
Revises: 773ce31eaab7
Create Date: 2026-07-25 13:16:38.426559
"""
from alembic import op
import sqlalchemy as sa


revision = '163afc80d70d'
down_revision = '773ce31eaab7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'company_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
