"""add project completed_at

Revision ID: 2860f97adbca
Revises: 5d90ee7f971c
Create Date: 2026-07-22 08:13:27.772829
"""
from alembic import op
import sqlalchemy as sa


revision = '2860f97adbca'
down_revision = '5d90ee7f971c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'completed_at')
    # ### end Alembic commands ###
