"""add currency to companies

Revision ID: 39fc1f101243
Revises: 8097aa6c1a92
Create Date: 2026-07-22 04:40:07.665023
"""
from alembic import op
import sqlalchemy as sa


revision = '39fc1f101243'
down_revision = '8097aa6c1a92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('currency', sa.String(length=3), nullable=False, server_default='USD'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'currency')
    # ### end Alembic commands ###