"""add request_id to overtime sessions

Revision ID: 3a484c037317
Revises: 5e05097c6f73
Create Date: 2026-07-17 10:48:59.179623
"""
from alembic import op
import sqlalchemy as sa


revision = '3a484c037317'
down_revision = '5e05097c6f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overtime_sessions', sa.Column('request_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'overtime_sessions', 'overtime_requests', ['request_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'overtime_sessions', type_='foreignkey')
    op.drop_column('overtime_sessions', 'request_id')
    # ### end Alembic commands ###
