"""add invoicing fields and invoice table

Revision ID: 5a8c102651a6
Revises: cb033f8c8d0b
Create Date: 2026-07-21 20:15:17.554318
"""
from alembic import op
import sqlalchemy as sa


revision = '5a8c102651a6'
down_revision = 'cb033f8c8d0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('hourly_fee', sa.Float(), nullable=False),
    sa.Column('total_hours', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('actual_working_hours', sa.Boolean(), nullable=False),
    sa.Column('pdf_url', sa.String(length=1024), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_company_id'), 'invoices', ['company_id'], unique=False)
    op.create_index(op.f('ix_invoices_user_id'), 'invoices', ['user_id'], unique=False)
    op.add_column('users', sa.Column('job_type', sa.String(length=20), nullable=False, server_default='full_time'))
    op.add_column('users', sa.Column('actual_working_hours', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('hourly_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hourly_fee')
    op.drop_column('users', 'actual_working_hours')
    op.drop_column('users', 'job_type')
    op.drop_index(op.f('ix_invoices_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_company_id'), table_name='invoices')
    op.drop_table('invoices')
    # ### end Alembic commands ###
