"""add project assignments

Revision ID: 5d90ee7f971c
Revises: 33c55cb2793e
Create Date: 2026-07-22 06:54:26.685109
"""
from alembic import op
import sqlalchemy as sa


revision = '5d90ee7f971c'
down_revision = '33c55cb2793e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_assignments',
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_assignments_project_id'), 'project_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_assignments_user_id'), 'project_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_assignments_user_id'), table_name='project_assignments')
    op.drop_index(op.f('ix_project_assignments_project_id'), table_name='project_assignments')
    op.drop_table('project_assignments')
    # ### end Alembic commands ###
