"""add overtime requests

Revision ID: 5e05097c6f73
Revises: bcd18395c7bd
Create Date: 2026-07-17 10:35:12.475801
"""
from alembic import op
import sqlalchemy as sa


revision = '5e05097c6f73'
down_revision = 'bcd18395c7bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overtime_requests',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('planned_start_time', sa.String(length=5), nullable=False),
    sa.Column('planned_end_time', sa.String(length=5), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decided_by', sa.BigInteger(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_requests_user_id'), 'overtime_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_overtime_requests_user_id'), table_name='overtime_requests')
    op.drop_table('overtime_requests')
    # ### end Alembic commands ###
