"""add sso_codes table

Revision ID: 773ce31eaab7
Revises: a1f9e2c7b410
Create Date: 2026-07-24 14:25:47.587579
"""
from alembic import op
import sqlalchemy as sa


revision = '773ce31eaab7'
down_revision = 'a1f9e2c7b410'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_codes',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sso_codes_code'), 'sso_codes', ['code'], unique=True)
    op.create_index(op.f('ix_sso_codes_user_id'), 'sso_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sso_codes_user_id'), table_name='sso_codes')
    op.drop_index(op.f('ix_sso_codes_code'), table_name='sso_codes')
    op.drop_table('sso_codes')
    # ### end Alembic commands ###
