"""add language to users and company_invites

Revision ID: 779d775178a0
Revises: 9824839e2f2b
Create Date: 2026-07-23 12:49:15.892957
"""
from alembic import op
import sqlalchemy as sa


revision = '779d775178a0'
down_revision = '9824839e2f2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=False, server_default='en'))
    op.add_column('company_invites', sa.Column('language', sa.String(length=10), nullable=False, server_default='en'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'language')
    op.drop_column('company_invites', 'language')
    # ### end Alembic commands ###
