"""add invoicing fields to company_invites

Revision ID: 8097aa6c1a92
Revises: 5a8c102651a6
Create Date: 2026-07-21 21:04:04.396405
"""
from alembic import op
import sqlalchemy as sa


revision = '8097aa6c1a92'
down_revision = '5a8c102651a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_invites', sa.Column('job_type', sa.String(length=20), nullable=False, server_default='full_time'))
    op.add_column('company_invites', sa.Column('actual_working_hours', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('company_invites', sa.Column('hourly_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_invites', 'hourly_fee')
    op.drop_column('company_invites', 'actual_working_hours')
    op.drop_column('company_invites', 'job_type')
    # ### end Alembic commands ###