"""add holidays table and holiday_country

Revision ID: 89ec77eec782
Revises: bf24e509fd3d
Create Date: 2026-07-18 04:40:26.056406
"""
from alembic import op
import sqlalchemy as sa


revision = '89ec77eec782'
down_revision = 'bf24e509fd3d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
