"""add holiday_country to invites

Revision ID: 956972d95a6a
Revises: 89ec77eec782
Create Date: 2026-07-18 04:57:24.273880
"""
from alembic import op
import sqlalchemy as sa


revision = '956972d95a6a'
down_revision = '89ec77eec782'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_invites', sa.Column('holiday_country', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_invites', 'holiday_country')
    # ### end Alembic commands ###
