"""add reason to overtime sessions

Revision ID: 95b18d3f3ff4
Revises: d3e80a2087fc
Create Date: 2026-07-17 09:32:39.404912
"""
from alembic import op
import sqlalchemy as sa


revision = '95b18d3f3ff4'
down_revision = 'd3e80a2087fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('overtime_sessions', sa.Column('reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('overtime_sessions', 'reason')
    # ### end Alembic commands ###
