"""add post_type to knowledge posts

Revision ID: a73ebcad84a4
Revises: eabb89eea8b6
Create Date: 2026-07-20 13:00:46.851172
"""
from alembic import op
import sqlalchemy as sa


revision = 'a73ebcad84a4'
down_revision = 'eabb89eea8b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_posts', sa.Column('post_type', sa.String(length=20), nullable=False, server_default='knowledge'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_posts', 'post_type')
    # ### end Alembic commands ###
