"""add ended_at to work outside overrides

Revision ID: b20556281a11
Revises: 0c305fa68ccb
Create Date: 2026-07-18 06:42:10.068379
"""
from alembic import op
import sqlalchemy as sa


revision = 'b20556281a11'
down_revision = '0c305fa68ccb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
