"""add per-employee timezone

Revision ID: bcd18395c7bd
Revises: 95b18d3f3ff4
Create Date: 2026-07-17 09:54:05.436254
"""
from alembic import op
import sqlalchemy as sa


revision = 'bcd18395c7bd'
down_revision = '95b18d3f3ff4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('working_hours_mode', sa.String(length=20), nullable=False, server_default=sa.text("'company_timezone'")))
    op.add_column('users', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('companies', 'working_hours_mode')
    # ### end Alembic commands ###
