"""add holidays table and holiday_country

Revision ID: bf24e509fd3d
Revises: e078f2cb1a3f
Create Date: 2026-07-17 11:42:38.349101
"""
from alembic import op
import sqlalchemy as sa


revision = 'bf24e509fd3d'
down_revision = 'e078f2cb1a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('country_code', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holidays_company_id'), 'holidays', ['company_id'], unique=False)
    op.create_index(op.f('ix_holidays_country_code'), 'holidays', ['country_code'], unique=False)
    op.create_index(op.f('ix_holidays_date'), 'holidays', ['date'], unique=False)
    op.add_column('users', sa.Column('holiday_country', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'holiday_country')
    op.drop_index(op.f('ix_holidays_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_country_code'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_company_id'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
