"""add last_health_prompt_at to attendance sessions

Revision ID: bf93ffaa962f
Revises: 8a94c76f4389
Create Date: 2026-07-17 08:02:16.596990
"""
from alembic import op
import sqlalchemy as sa


revision = 'bf93ffaa962f'
down_revision = '8a94c76f4389'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_sessions', sa.Column('last_health_prompt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_sessions', 'last_health_prompt_at')
    # ### end Alembic commands ###
