"""verify sync after recovery

Revision ID: cb033f8c8d0b
Revises: d47e9c1b2a03
Create Date: 2026-07-20 19:14:04.381464
"""
from alembic import op
import sqlalchemy as sa


revision = 'cb033f8c8d0b'
down_revision = 'd47e9c1b2a03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
