"""recover holidays table and company_invites columns (undo bad autogen)

Revision ID: d47e9c1b2a03
Revises: c36d8b3af392
Create Date: 2026-07-20 19:00:00.000000

Guarded -- this was a historical recovery from a bad autogenerated
migration that incorrectly dropped these. On a fresh database, 0001
already creates holidays and the company_invites columns from current
model metadata, so this recovery step has nothing to do.
"""
from alembic import op
import sqlalchemy as sa


revision = 'd47e9c1b2a03'
down_revision = 'c36d8b3af392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    if 'holidays' not in inspector.get_table_names():
        op.create_table('holidays',
            sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
            sa.Column('company_id', sa.BigInteger(), autoincrement=False, nullable=False),
            sa.Column('country_code', sa.String(length=20), autoincrement=False, nullable=False),
            sa.Column('date', sa.Date(), autoincrement=False, nullable=False),
            sa.Column('name', sa.String(length=255), autoincrement=False, nullable=False),
            sa.Column('is_custom', sa.Boolean(), autoincrement=False, nullable=False),
            sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='holidays_company_id_fkey', ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id', name='holidays_pkey'),
        )
        op.create_index('ix_holidays_company_id', 'holidays', ['company_id'], unique=False)
        op.create_index('ix_holidays_country_code', 'holidays', ['country_code'], unique=False)
        op.create_index('ix_holidays_date', 'holidays', ['date'], unique=False)

    invite_columns = {c['name'] for c in inspector.get_columns('company_invites')}
    if 'timezone' not in invite_columns:
        op.add_column('company_invites', sa.Column('timezone', sa.String(length=64), nullable=True))
    if 'holiday_country' not in invite_columns:
        op.add_column('company_invites', sa.Column('holiday_country', sa.String(length=20), nullable=True))


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    invite_columns = {c['name'] for c in inspector.get_columns('company_invites')}

    if 'holiday_country' in invite_columns:
        op.drop_column('company_invites', 'holiday_country')
    if 'timezone' in invite_columns:
        op.drop_column('company_invites', 'timezone')

    if 'holidays' in inspector.get_table_names():
        op.drop_index('ix_holidays_date', table_name='holidays')
        op.drop_index('ix_holidays_country_code', table_name='holidays')
        op.drop_index('ix_holidays_company_id', table_name='holidays')
        op.drop_table('holidays')
