"""add timezone to company invites

Revision ID: e078f2cb1a3f
Revises: 3a484c037317
Create Date: 2026-07-17 11:21:28.317102
"""
from alembic import op
import sqlalchemy as sa


revision = 'e078f2cb1a3f'
down_revision = '3a484c037317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_invites', sa.Column('timezone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_invites', 'timezone')
    # ### end Alembic commands ###
