"""add extra_data_json to notifications

Revision ID: f906f1500939
Revises: 7456c5c99e07
Create Date: 2026-07-20 16:24:44.023069
"""
from alembic import op
import sqlalchemy as sa


revision = 'f906f1500939'
down_revision = '7456c5c99e07'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('extra_data_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'extra_data_json')
    # ### end Alembic commands ###
