"""add late/early tracking and break sessions

Revision ID: fecd79cc1d4e
Revises: 956972d95a6a
Create Date: 2026-07-18 06:02:15.107948
"""
from alembic import op
import sqlalchemy as sa


revision = 'fecd79cc1d4e'
down_revision = '956972d95a6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('break_sessions',
    sa.Column('attendance_session_id', sa.BigInteger(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['attendance_session_id'], ['attendance_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_break_sessions_attendance_session_id'), 'break_sessions', ['attendance_session_id'], unique=False)
    op.add_column('attendance_sessions', sa.Column('late_minutes', sa.Integer(), nullable=True))
    op.add_column('attendance_sessions', sa.Column('early_checkout_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendance_sessions', 'early_checkout_minutes')
    op.drop_column('attendance_sessions', 'late_minutes')
    op.drop_index(op.f('ix_break_sessions_attendance_session_id'), table_name='break_sessions')
    op.drop_table('break_sessions')
    # ### end Alembic commands ###
